### ISSUE TITLE
Rename WhiteNoise (TBD)

### ISSUE THREAD

**Issue by raprasad** [opendifferentialprivacy/smartnoise-core#260]
- notice of name change up on 6/18
- waiting on name change agreement
---
## smartnoise-core (rust)
- [x] renaming
  - [x] crate creation

## smartnoise-core-python
  - [x] renaming
  - [x] pypi package
    - [x] windows pypi package ([see 46](https://github.com/opendifferentialprivacy/smartnoise-core-python/issues/46))

## smartnoise-samples
- [x] HU notebook renaming
- [x] README staged
- [x] repository rename, other samples files (MS/JH)
- [x] MS notebooks/files, SQL

## Misc
- [x] support email, changed to whitenoise@opendp.io
- [x] gitter room name change (MS)

## smartnoise website
  - [x] create repository
  - [x] change links
  - [x] DNS record updates
  - [x] redirect current repo
  - [ ] google tracking (need to ask MS)

**Comment by amanjeev** [comment]
Is there an estimate how long will the renaming take? Thank you.

**Comment by raprasad** [comment]
travis.yml ->   WHITENOISE_RELEASE=True

**Comment by raprasad** [comment]
Almost there. Last items:
- [ ] update crates so readme has correct link to sn-sdk, instead of sn-system
- [ ] reconstruction notebook being fixed
- correspondence in progress re: microsite google tracking

**Comment by raprasad** [comment]
closing

**Comment by raprasad** [comment]
(closing after MS email)
